### ISSUE TITLE
New version with undefined type error

### ISSUE THREAD

**Issue by WeNeedThePoh** [phrase/phrase-go#9]
Hello!

I tried to update to the new version v2.4.0 and came across an undefined type error.

https://github.com/phrase/phrase-go/blob/master/model_invitation.go#L22
This `Items` type seems it's not implemented or at least does not exist in this package.

Also, the CI failed here:
https://github.com/phrase/phrase-go/commit/09d6741d7924f68aa8f264db038fe4bd867a705e#diff-d5cbbd461f33220c20c9a3c799392fd37a8ad2c88802b7ff32ffbf4512d497e8R22

If more information is needed let me know, glad to help!

Thanks!

**Comment by theSoenke** [comment]
Hi @WeNeedThePoh, thanks for reporting this. We've also noticed this and are currently looking into it for a fix

**Comment by sbruhns** [comment]
Hi @WeNeedThePoh, we released a new fixed version `v2.5.0`.
